name: validate-yaml

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML files
        run: yamllint point/* comparison/* inheritance.yaml relation.yaml
